### ISSUE TITLE
ttlMap.Put does not update existing data

### ISSUE THREAD

**Issue by glenvan** [jftuga/ttlMap#7]
I noticed a bug in `ttlMap.Put()`: the value is only set in the `item.Value` when the item is initially created, not on subsequent calls to `Put` with the same key.

```go
package main

import (
	"fmt"
	"time"

	"github.com/jftuga/TtlMap"
)

func main() {
	tm := TtlMap.New[string](time.Second*4, 3, time.Second, true)
	defer tm.Close()

	tm.Put("example", "original")
	tm.Put("example", "revised")

	fmt.Printf("Example value is %s\n", tm.Get("example"))
	// Output:
	// Example value is original
}
```

Setting the value just needs to be moved out of the [`if !ok` scope](https://github.com/jftuga/TtlMap/blob/main/ttlMap.go#L82).

**Comment by jftuga** [comment]
Thank you for reporting this. 

This problem is fixed and is included in the `main` branch as well as the `v1.5.1` release.  I also added a test in `ttlMap_test.go` to check for this.

* https://github.com/jftuga/TtlMap/blob/main/ttlMap.go#L78
* https://github.com/jftuga/TtlMap/blob/main/ttlMap_test.go#L284
